name: Production deployment

on:
  pull_request:
    types: [labeled]

  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: whatsapp-test-app
  AZURE_WEBAPP_PACKAGE_PATH: "./whatsapp-backend" # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "14.10.1" # set this to the node version to use
jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'stage')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        working-directory: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        working-directory: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm install
          npm run build --if-present
          npm run test --if-present

  Deploy-to-Azure:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy api to Azure
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
      - name: Azure logout
        run: |
          az logout
